language: generic 

sudo: required

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t wangbaoming/docker-react .

script:
    - docker run -e CI=true wangbaoming/docker-react npm run test